import type { Project } from "./types";

export const projects: Project[] = [
  {
    id: "setup-environment",
    stepIndex: 1,
    title: "From Idea to Live URL — Your First AI-Native Build",
    level: "Beginner",
    problem:
      "As a PM with no coding background, building a product from scratch feels blocked by not knowing how to code. The traditional path — learn HTML, then CSS, then JavaScript, then a framework — takes months before you ship anything real. In the AI era, that path is obsolete. You can go from idea to live product in a single session without writing a line of code manually.",
    task: "Set up your AI-native builder stack, use the meta-prompt technique to turn a rough idea into a structured spec, build a working app with v0.dev, and deploy it to a live URL on Vercel — all in one session.",
    tools: ["Claude", "ChatGPT", "v0.dev", "Vercel", "GitHub", "Cursor"],
    skills: ["Meta-Prompting", "Product Specification", "AI-Native Building", "Deployment"],
    deliverables: [
      "Accounts created: Claude or ChatGPT, v0.dev, Vercel, GitHub, Cursor",
      "A product spec written via the meta-prompt interview technique",
      "A working app generated by v0.dev from your spec",
      "App deployed live at a Vercel URL you can share",
      "Cursor installed and ready for Step 2",
    ],
    trySteps: [
      "Create free accounts on v0.dev, Vercel, and GitHub. Install Cursor (free tier). These are your core tools for the entire journey.",
      "Open Claude or ChatGPT. Paste this meta-prompt: 'You are a v0 Product Manager helping me build a product. Ask me 10 questions one at a time to understand my idea, then write a detailed spec ready to paste into v0.' Answer each question specifically — vague answers produce vague results.",
      "Review the generated spec before pasting it into v0. Look for: missing features, unclear requirements, scope that's too big for a first build. Edit it down ruthlessly. The more focused the spec, the better the output.",
      "Paste the final spec into v0.dev. When the first version appears, treat it like a design review: what's right, what's wrong, what's missing. Use follow-up prompts to iterate — 'make the header smaller', 'add a progress bar below the hero', 'remove the sidebar'. This is product work.",
      "When you're happy with it, click Deploy in v0 → connect your Vercel account → get your live URL. Share it with at least one person and ask: 'What's confusing about this?'",
    ],
    resources: [
      { label: "v0.dev", url: "https://v0.dev" },
      { label: "Vercel", url: "https://vercel.com" },
      { label: "Cursor", url: "https://cursor.com" },
      {
        label: "Anthropic Prompting Guide",
        url: "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview",
      },
      {
        label: "Example: PM to FSB app (built in this step)",
        url: "https://v0-frompmto.vercel.app",
      },
    ],
  },
  {
    id: "prompting-fundamentals",
    stepIndex: 2,
    title: "From Vague Ask to Clear Prompt Brief",
    level: "Beginner",
    problem:
      "AI-assisted development is a core skill, but most people write vague prompts and get mediocre output.",
    task: "Learn structured prompting techniques. Write, test, and iterate on prompts for code generation, debugging, and explanation tasks.",
    tools: ["ChatGPT", "Claude", "v0", "Markdown"],
    skills: ["Prompt Engineering", "Critical Thinking", "Iteration"],
    deliverables: [
      "5 tested prompts for different use cases",
      "Before/after comparison of prompt quality",
      "A personal prompt template library",
      "Notes on what makes prompts effective",
    ],
    trySteps: [
      "Write a basic prompt asking for a function",
      "Refine it with context, constraints, and examples",
      "Test the same task across two AI tools",
      "Document patterns that produce better results",
      "Build a reusable prompt template in Markdown",
    ],
    resources: [
      { label: "Prompt Engineering Guide", url: "https://www.promptingguide.ai/" },
      { label: "OpenAI Best Practices", url: "https://platform.openai.com/docs/guides/prompt-engineering" },
    ],
  },
  {
    id: "simple-landing-page",
    stepIndex: 3,
    title: "Ship a Simple Landing Page",
    level: "Beginner",
    problem:
      "You have ideas but no public presence. Shipping a real page builds confidence and shows you can deliver.",
    task: "Design and deploy a single-page landing page using Next.js and Tailwind CSS. Include a hero, features section, and CTA.",
    tools: ["Next.js", "Tailwind CSS", "Vercel", "v0"],
    skills: ["HTML/CSS", "Component Design", "Deployment", "Responsive Design"],
    deliverables: [
      "A deployed landing page on Vercel",
      "Responsive layout (mobile + desktop)",
      "Hero section with headline and CTA",
      "Features section with at least 3 items",
      "Footer with links",
    ],
    trySteps: [
      "Scaffold a Next.js project with `create-next-app`",
      "Build the hero section with Tailwind CSS",
      "Add a features grid with icons and descriptions",
      "Make the layout responsive for mobile",
      "Deploy to Vercel and share the link",
    ],
    resources: [
      { label: "Next.js Docs", url: "https://nextjs.org/docs" },
      { label: "Tailwind CSS Docs", url: "https://tailwindcss.com/docs" },
    ],
  },
  {
    id: "crud-app",
    stepIndex: 4,
    title: "Build a Small CRUD App",
    level: "Beginner",
    problem:
      "Static pages are limited. Real apps need to create, read, update, and delete data. Understanding CRUD is foundational.",
    task: "Build a task manager app with mock data. Implement all four CRUD operations with a clean UI and state management.",
    tools: ["Next.js", "React", "TypeScript", "shadcn/ui"],
    skills: ["State Management", "CRUD Operations", "TypeScript", "Component Architecture"],
    deliverables: [
      "Working task manager with add/edit/delete",
      "TypeScript types for all data models",
      "Clean component hierarchy",
      "Loading and empty states",
      "Form validation",
    ],
    trySteps: [
      "Define your data model with TypeScript interfaces",
      "Build a list component that renders tasks",
      "Add a form to create new tasks",
      "Implement edit and delete with confirmation",
      "Add filtering or sorting as a bonus",
    ],
    resources: [
      { label: "React Docs", url: "https://react.dev" },
      { label: "shadcn/ui", url: "https://ui.shadcn.com" },
    ],
  },
  {
    id: "add-auth",
    stepIndex: 5,
    title: "Add Authentication",
    level: "Intermediate",
    problem:
      "Most apps need user accounts. Auth is complex, but understanding the basics is essential for any full-stack builder.",
    task: "Add login and signup flows to your app. Implement session management and protect routes based on auth status.",
    tools: ["Next.js", "Cookies", "bcrypt", "Middleware"],
    skills: ["Authentication", "Session Management", "Security Basics", "Protected Routes"],
    deliverables: [
      "Login and signup pages",
      "Session-based auth with cookies",
      "Protected dashboard route",
      "User menu with name and logout",
      "Error handling for auth failures",
    ],
    trySteps: [
      "Create login and signup form components",
      "Implement a mock user store",
      "Set up session management with cookies",
      "Add middleware to protect routes",
      "Build a user dropdown with logout",
    ],
    resources: [
      { label: "Auth.js", url: "https://authjs.dev" },
      { label: "Next.js Middleware", url: "https://nextjs.org/docs/app/building-your-application/routing/middleware" },
    ],
  },
  {
    id: "search-filtering",
    stepIndex: 6,
    title: "Add Search and Filtering",
    level: "Intermediate",
    problem:
      "Users can't find what they need in growing datasets. Search and filtering are table-stakes features.",
    task: "Implement a global search with filters across a dataset. Support real-time search, category filters, and clear result presentation.",
    tools: ["Next.js", "React", "URL Search Params", "Debounce"],
    skills: ["Search UX", "Filtering Logic", "URL State", "Performance"],
    deliverables: [
      "Global search input in navigation",
      "Search results with highlighting",
      "Category/tag filter controls",
      "URL-synced search state",
      "No-results and loading states",
    ],
    trySteps: [
      "Build a search input component with debounce",
      "Implement text search across title and tags",
      "Add filter dropdowns for categories",
      "Sync search params to the URL",
      "Design empty and loading states",
    ],
    resources: [
      { label: "useSearchParams", url: "https://nextjs.org/docs/app/api-reference/functions/use-search-params" },
    ],
  },
  {
    id: "analytics-events",
    stepIndex: 7,
    title: "Add Analytics Events",
    level: "Intermediate",
    problem:
      "You can't improve what you can't measure. Analytics help you understand user behavior and make data-driven decisions.",
    task: "Instrument your app with event tracking. Track page views, button clicks, form submissions, and custom events.",
    tools: ["Vercel Analytics", "Custom Events", "TypeScript"],
    skills: ["Analytics", "Event Tracking", "Data Modeling", "Product Thinking"],
    deliverables: [
      "Analytics SDK integrated",
      "Page view tracking on all routes",
      "Custom events for key actions",
      "Event naming convention documented",
      "Dashboard showing tracked events",
    ],
    trySteps: [
      "Install and configure Vercel Analytics",
      "Add page view tracking to the layout",
      "Define a naming convention for custom events",
      "Track 5+ meaningful user actions",
      "Review the analytics dashboard",
    ],
    resources: [
      { label: "Vercel Analytics", url: "https://vercel.com/docs/analytics" },
    ],
  },
  {
    id: "mini-rag-demo",
    stepIndex: 8,
    title: "Build a Mini RAG Demo",
    level: "Advanced",
    problem:
      "AI apps need context to be useful. Retrieval-Augmented Generation (RAG) connects LLMs to your own data.",
    task: "Build a simple RAG pipeline: index a small dataset, retrieve relevant chunks based on a query, and generate an answer using an LLM.",
    tools: ["AI SDK", "OpenAI", "Vector Search", "TypeScript"],
    skills: ["RAG Architecture", "Embeddings", "Prompt Chaining", "AI Integration"],
    deliverables: [
      "A small indexed dataset (5-10 documents)",
      "Query input that retrieves relevant chunks",
      "LLM-generated answer using retrieved context",
      "UI showing sources alongside the answer",
      "Error handling for API failures",
    ],
    trySteps: [
      "Prepare a small dataset of text documents",
      "Generate embeddings for each document",
      "Implement a similarity search function",
      "Chain retrieval results into an LLM prompt",
      "Build a UI with query input and answer display",
    ],
    resources: [
      { label: "AI SDK Docs", url: "https://sdk.vercel.ai" },
      { label: "RAG Explained", url: "https://www.pinecone.io/learn/retrieval-augmented-generation/" },
    ],
  },
  {
    id: "evaluation-checklist",
    stepIndex: 9,
    title: "Add Evaluation Checklist",
    level: "Advanced",
    problem:
      "Shipping fast is good, but shipping quality matters more. You need a systematic way to evaluate your work.",
    task: "Create a reusable evaluation checklist for your projects. Cover code quality, accessibility, performance, and security.",
    tools: ["Lighthouse", "ESLint", "axe", "TypeScript"],
    skills: ["Code Review", "Accessibility", "Performance", "Quality Assurance"],
    deliverables: [
      "Evaluation checklist template",
      "Automated checks with ESLint rules",
      "Lighthouse score baseline",
      "Accessibility audit report",
      "Security review checklist",
    ],
    trySteps: [
      "Run Lighthouse on your deployed app",
      "Configure ESLint with strict rules",
      "Run an accessibility audit with axe",
      "Create a checklist template in Markdown",
      "Score one of your previous projects",
    ],
    resources: [
      { label: "Lighthouse", url: "https://developer.chrome.com/docs/lighthouse" },
      { label: "axe DevTools", url: "https://www.deque.com/axe/" },
    ],
  },
  {
    id: "deploy-workflow",
    stepIndex: 10,
    title: "Deploy Workflow",
    level: "Advanced",
    problem:
      "Manual deployments are error-prone and slow. A repeatable deploy workflow saves time and prevents mistakes.",
    task: "Set up a CI/CD pipeline with automated testing, preview deployments, and production deploys on merge.",
    tools: ["Vercel", "GitHub Actions", "Environment Variables", "Git"],
    skills: ["CI/CD", "DevOps Basics", "Automation", "Environment Management"],
    deliverables: [
      "GitHub Actions workflow file",
      "Automated tests running on PR",
      "Preview deployments on branches",
      "Production deploy on main merge",
      "Environment variable management",
    ],
    trySteps: [
      "Create a GitHub Actions workflow file",
      "Add a test step that runs on every PR",
      "Configure Vercel for preview deployments",
      "Set up environment variables in Vercel",
      "Test the full pipeline end-to-end",
    ],
    resources: [
      { label: "Vercel Git Integration", url: "https://vercel.com/docs/git" },
      { label: "GitHub Actions", url: "https://docs.github.com/en/actions" },
    ],
  },
  {
    id: "capstone-template",
    stepIndex: 11,
    title: "Build a Capstone Project Template",
    level: "Advanced",
    problem:
      "Starting from scratch every time is inefficient. A reusable project template accelerates future work.",
    task: "Create a production-ready project template with auth, database, UI components, and deployment configured out of the box.",
    tools: ["Next.js", "Tailwind CSS", "shadcn/ui", "Supabase", "Vercel"],
    skills: ["Architecture", "Template Design", "Documentation", "DX"],
    deliverables: [
      "A cloneable project template repo",
      "Pre-configured auth and database",
      "Component library with shadcn/ui",
      "README with setup instructions",
      "Deploy-to-Vercel button",
    ],
    trySteps: [
      "Start with a fresh Next.js project",
      "Add Tailwind CSS and shadcn/ui",
      "Configure authentication",
      "Set up database with migrations",
      "Write clear documentation and add a deploy button",
    ],
    resources: [
      { label: "Vercel Templates", url: "https://vercel.com/templates" },
      { label: "shadcn/ui", url: "https://ui.shadcn.com" },
    ],
  },
  {
    id: "portfolio-polish",
    stepIndex: 12,
    title: "Portfolio Polish and Public Sharing",
    level: "Advanced",
    problem:
      "Your work is invisible if no one can see it. A polished portfolio turns completed projects into career opportunities.",
    task: "Polish your portfolio with project showcases, a bio, links to live demos, and an exportable/shareable public view.",
    tools: ["Next.js", "Tailwind CSS", "Vercel", "Open Graph"],
    skills: ["Portfolio Design", "Storytelling", "SEO", "Personal Branding"],
    deliverables: [
      "Portfolio page with project cards",
      "Each project links to live demo + source",
      "Open Graph meta tags for sharing",
      "Responsive and accessible design",
      "Shareable public URL",
    ],
    trySteps: [
      "List all completed projects with descriptions",
      "Design a portfolio page layout",
      "Add project cards with screenshots and links",
      "Configure Open Graph meta tags",
      "Share your portfolio URL publicly",
    ],
    resources: [
      { label: "Open Graph Protocol", url: "https://ogp.me/" },
      { label: "Vercel OG", url: "https://vercel.com/docs/og-image-generation" },
    ],
  },
];

export function getProjectById(id: string): Project | undefined {
  return projects.find((p) => p.id === id);
}

export function getProjectByStep(step: number): Project | undefined {
  return projects.find((p) => p.stepIndex === step);
}
